"""PDF and Excel report generation for the TPM Competency Matrix.

Libraries used
--------------
* **PDF**  - ``reportlab`` (pure Python, no system dependency) with
  ``svglib`` to embed the spider chart generated by :mod:`app.radar`. The
  chart is produced by our own code and converted to a ReportLab
  ``Drawing``, so the printed report and the on-screen dashboard share one
  geometry implementation and can never drift apart.
* **Excel** - ``openpyxl``.

If you later prefer a different toolchain, the substitution points are
narrow: :func:`_write_pdf` and :func:`_write_workbook` are the only places
that touch either library. See ``docs/REPORTING.md`` for alternatives
(xlsxwriter, WeasyPrint/Chromium for HTML->PDF, Tabulator, etc.).

All five required reports are produced by this module:
    1. individual_competency_report   (includes the spider chart)
    2. department_competency_report
    3. competency_gap_report
    4. training_needs_report
    5. competency_progress_report
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from svglib.svglib import svg2rlg

from .radar import render_radar_svg
from .repository import Repository
from .scoring import GapStatus, Priority

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = ROOT / "data" / "reports"

HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(color="FFFFFF", bold=True, size=11)
TITLE_FONT = Font(bold=True, size=14)


@dataclass(frozen=True, slots=True)
class ReportArtifact:
    """Paths of the files produced for one report."""

    name: str
    title: str
    pdf: Path | None
    xlsx: Path | None
    row_count: int


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "t", parent=base["Title"], fontSize=18, spaceAfter=4, alignment=TA_CENTER
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontSize=12, spaceBefore=12, spaceAfter=6
        ),
        "body": ParagraphStyle("b", parent=base["BodyText"], fontSize=9.5),
        "small": ParagraphStyle("s", parent=base["BodyText"], fontSize=8, textColor=colors.HexColor("#555555")),
    }


def _fmt_pct(value: float | None) -> str:
    return "-" if value is None else f"{value:.1f}%"


def _fmt_rating(value: int | None) -> str:
    return "Not assessed" if value is None else str(value)


# ---------------------------------------------------------------------------
# PDF primitives
# ---------------------------------------------------------------------------

def _pdf_header(title: str, subtitle: str, styles: dict[str, ParagraphStyle]) -> list:
    return [
        Paragraph(title, styles["title"]),
        Paragraph(subtitle, styles["small"]),
        Spacer(1, 10),
    ]


def _pdf_table(
    headers: Sequence[str],
    rows: Iterable[Sequence[object]],
    *,
    widths: Sequence[float] | None = None,
    status_colour: dict[int, object] | None = None,
) -> Table:
    data = [list(headers)]
    for row in rows:
        data.append(["" if cell is None else str(cell) for cell in row])

    table = Table(data, repeatRows=1, colWidths=widths)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#BFC9D0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F7F9")]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    if status_colour:
        for index, colour in status_colour.items():
            style.append(("TEXTCOLOR", (index, 1), (index, -1), colour))
    table.setStyle(TableStyle(style))
    return table


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#666666"))
    canvas.drawString(15 * mm, 10 * mm, "Hume - TPM Maintenance Competency Matrix")
    canvas.drawRightString(
        landscape(A4)[0] - 15 * mm if doc.pagesize[0] > doc.pagesize[1] else A4[0] - 15 * mm,
        10 * mm,
        f"Page {doc.page}",
    )
    canvas.drawCentredString(doc.pagesize[0] / 2, 6 * mm, dt.date.today().isoformat())
    canvas.restoreState()


def _write_pdf(path: Path, story: list, *, landscape_mode: bool = False) -> Path:
    pagesize = landscape(A4) if landscape_mode else A4
    doc = SimpleDocTemplate(
        str(path),
        pagesize=pagesize,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
        topMargin=14 * mm,
        bottomMargin=16 * mm,
        title=path.stem,
        author="Hume TPM System",
    )
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return path


def _write_workbook(
    path: Path, sheets: dict[str, tuple[Sequence[str], Iterable[Sequence[object]]]]
) -> Path:
    workbook = Workbook()
    workbook.remove(workbook.active)
    for title, (headers, rows) in sheets.items():
        sheet = workbook.create_sheet(title=title[:31])
        sheet.append(list(headers))
        for cell in sheet[1]:
            cell.fill = HEADER_FILL
            cell.font = HEADER_FONT
            cell.alignment = Alignment(horizontal="center", vertical="center")
        body: list[list[object]] = []
        for row in rows:
            record = ["" if cell is None else cell for cell in row]
            sheet.append(record)
            body.append(record)
        for index, header in enumerate(headers):
            longest = max([len(str(header))] + [len(str(r[index])) for r in body])
            sheet.column_dimensions[get_column_letter(index + 1)].width = min(max(longest + 2, 10), 46)
        sheet.freeze_panes = "A2"
        sheet.auto_filter.ref = sheet.dimensions
    workbook.save(str(path))
    return path


# ---------------------------------------------------------------------------
# Report 1 - Individual Competency Report (with spider chart)
# ---------------------------------------------------------------------------

def individual_competency_report(
    repo: Repository,
    employee_id: str,
    output_dir: Path = DEFAULT_OUTPUT,
    *,
    fmt: tuple[str, ...] = ("pdf", "xlsx"),
) -> ReportArtifact:
    profile = repo.get_profile(employee_id)
    employee = profile.employee
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"01_individual_{employee.employee_number.replace('/', '-')}"

    header_cells = [
        ["Employee", employee.full_name],
        ["Employee No.", employee.employee_number],
        ["Position", employee.position_title],
        ["Department", employee.department],
        ["Supervisor", employee.supervisor or "-"],
        ["Date Joined", f"{employee.join_date} ({employee.years_of_experience}y)"],
        [
            "Overall Competency",
            f"{profile.overall.percentage:.1f}%  "
            f"({profile.overall.total_rating}/{profile.overall.max_possible_rating})",
        ],
        [
            "Assessment Coverage",
            f"{profile.overall.assessed_count}/{profile.overall.total_count} assessed "
            f"({profile.overall.coverage_percentage:.1f}%)",
        ],
    ]

    matrix_rows = [
        [
            gap.competency_name,
            gap.category,
            _fmt_rating(gap.rating_score),
            _fmt_rating(gap.required_score),
            _fmt_pct(gap.current_percentage),
            f"{gap.required_percentage}%",
            str(gap.status),
            str(gap.priority) if gap.is_actionable else "-",
            str(gap.shortfall) if gap.is_actionable else "0",
        ]
        for gap in profile.gaps
    ]
    matrix_headers = [
        "Competency",
        "Category",
        "Current",
        "Required",
        "Current %",
        "Required %",
        "Status",
        "Priority",
        "Shortfall",
    ]

    history_rows = [
        [
            a.assessment_date,
            a.cycle_name,
            a.assessor_name,
            f"{a.total_rating}/{a.max_possible_rating}",
            f"{a.overall_percentage:.1f}%",
            a.remarks or "",
        ]
        for a in profile.assessments
    ]
    training_rows = [
        [t.completion_date, t.title, t.provider or "", t.status, t.reassessment_cycle or ""]
        for t in profile.training
    ]

    pdf_path: Path | None = None
    if "pdf" in fmt:
        styles = _styles()
        available_width = landscape(A4)[0] - 30 * mm
        story = _pdf_header(
            "Individual Competency Report",
            f"{employee.full_name} - {employee.position_title} - generated {dt.date.today().isoformat()}",
            styles,
        )
        story.append(_pdf_table(["Field", "Value"], header_cells, widths=[45 * mm, available_width - 45 * mm]))
        story.append(Spacer(1, 8))

        story.append(Paragraph("Competency Spider Chart", styles["h2"]))
        drawing = _svg_drawing(profile, max_width=available_width, max_height=150 * mm)
        if drawing is not None:
            story.append(drawing)
            story.append(Spacer(1, 4))
            story.append(
                Paragraph(
                    "Solid blue polygon = current competency. Dashed amber polygon = level "
                    "required for the position. A break in the blue polygon marks a "
                    "competency that has not yet been assessed (not a score of zero).",
                    styles["small"],
                )
            )
            story.append(Spacer(1, 8))

        story.append(
            KeepTogether(
                [
                    Paragraph("Competency Matrix", styles["h2"]),
                    _pdf_table(
                        matrix_headers,
                        matrix_rows,
                        widths=[62 * mm, 26 * mm, 17 * mm, 17 * mm, 17 * mm, 19 * mm, 20 * mm, 19 * mm, 16 * mm],
                        status_colour={6: colors.HexColor("#333333")},
                    ),
                ]
            )
        )

        story.append(Paragraph("Assessment History", styles["h2"]))
        story.append(
            _pdf_table(
                ["Date", "Cycle", "Assessor", "Score", "Overall", "Remarks"],
                history_rows or [["-"] * 6],
                widths=[22 * mm, 42 * mm, 32 * mm, 18 * mm, 16 * mm, 87 * mm],
            )
        )
        story.append(Paragraph("Training History", styles["h2"]))
        story.append(
            _pdf_table(
                ["Completed", "Training", "Provider", "Status", "Reassessment Cycle"],
                training_rows or [["-"] * 5],
                widths=[22 * mm, 62 * mm, 42 * mm, 20 * mm, 71 * mm],
            )
        )
        pdf_path = _write_pdf(output_dir / f"{stem}.pdf", story, landscape_mode=True)

    xlsx_path: Path | None = None
    if "xlsx" in fmt:
        xlsx_path = _write_workbook(
            output_dir / f"{stem}.xlsx",
            {
                "Summary": (["Field", "Value"], header_cells),
                "Competency Matrix": (matrix_headers, matrix_rows),
                "Assessment History": (
                    ["Assessment Date", "Cycle", "Assessor", "Score", "Overall %", "Remarks"],
                    history_rows,
                ),
                "Training History": (
                    ["Completion Date", "Training", "Provider", "Status", "Reassessment Cycle"],
                    training_rows,
                ),
            },
        )

    return ReportArtifact(
        name="individual_competency_report",
        title=f"Individual Competency Report - {employee.full_name}",
        pdf=pdf_path,
        xlsx=xlsx_path,
        row_count=len(matrix_rows),
    )


def _svg_drawing(profile, *, max_width: float, max_height: float):
    """Convert the spider-chart SVG into a ReportLab Drawing that fits the frame."""
    import io

    svg = render_radar_svg(profile.scores, size=1000, employee_name=profile.employee.full_name)
    drawing = svg2rlg(io.BytesIO(svg.encode("utf-8")))
    if drawing is None:
        return None
    scale = min(max_width / drawing.width, max_height / drawing.height)
    drawing.width *= scale
    drawing.height *= scale
    drawing.scale(scale, scale)
    return drawing


# ---------------------------------------------------------------------------
# Report 2 - Department Competency Report
# ---------------------------------------------------------------------------

def department_competency_report(
    repo: Repository,
    department: str,
    output_dir: Path = DEFAULT_OUTPUT,
    *,
    fmt: tuple[str, ...] = ("pdf", "xlsx"),
) -> ReportArtifact:
    employees = repo.list_employees(department=department)
    summary = repo.department_summary(department)
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"02_department_{department.replace(' ', '_').replace('&', 'and')}"

    headers = ["Employee No.", "Name", "Position", "Supervisor", "Exp.", "Overall %", "Assessed", "Coverage %", "Gaps"]
    rows: list[list[object]] = []
    for employee in employees:
        _, overall, gaps = repo.build_matrix(employee.id)
        rows.append(
            [
                employee.employee_number,
                employee.full_name,
                employee.position_title,
                employee.supervisor or "-",
                f"{employee.years_of_experience}y" if employee.years_of_experience is not None else "-",
                f"{overall.percentage:.1f}%",
                f"{overall.assessed_count}/{overall.total_count}",
                f"{overall.coverage_percentage:.1f}%",
                str(sum(1 for g in gaps if g.status is GapStatus.GAP)),
            ]
        )
    rows.sort(key=lambda r: float(str(r[5]).rstrip("%")), reverse=True)

    # Competency x position average, to expose which axes the team lacks.
    axis_rows: list[list[object]] = []
    totals: dict[str, list[int]] = {}
    names: dict[str, str] = {}
    for employee in employees:
        scores, _, _ = repo.build_matrix(employee.id)
        for score in scores:
            if score.required_score <= 0 or score.rating_score is None:
                continue
            totals.setdefault(score.competency_id, []).append(score.rating_score)
            names[score.competency_id] = score.competency_name
    for competency_id, ratings in totals.items():
        axis_rows.append(
            [
                names[competency_id],
                len(ratings),
                f"{sum(ratings) / len(ratings):.2f}",
                f"{(sum(ratings) / len(ratings)) * 20:.1f}%",
            ]
        )
    axis_rows.sort(key=lambda r: float(str(r[2])), reverse=True)

    pdf_path: Path | None = None
    if "pdf" in fmt:
        styles = _styles()
        story = _pdf_header(
            "Department Competency Report",
            f"{department} - {summary.employee_count} employees - generated {dt.date.today().isoformat()}",
            styles,
        )
        story.append(
            _pdf_table(
                ["Metric", "Value"],
                [
                    ["Employees", summary.employee_count],
                    ["Average overall competency", f"{summary.average_percentage:.1f}%"],
                    ["Highest / Lowest", f"{summary.maximum_percentage:.1f}% / {summary.minimum_percentage:.1f}%"],
                    ["Competencies achieved", summary.achieved_count],
                    ["Competencies with a gap", summary.gap_count],
                    ["Competencies not yet assessed", summary.unassessed_count],
                    ["Critical action items", summary.critical_gap_count],
                ],
                widths=[70 * mm, 80 * mm],
            )
        )
        story.append(Paragraph("Employees by Overall Competency", styles["h2"]))
        story.append(
            _pdf_table(
                headers,
                rows or [["-"] * len(headers)],
                widths=[24 * mm, 40 * mm, 45 * mm, 38 * mm, 12 * mm, 18 * mm, 18 * mm, 20 * mm, 14 * mm],
            )
        )
        story.append(Paragraph("Team Average by Competency (weakest first)", styles["h2"]))
        story.append(
            _pdf_table(
                ["Competency", "Staff Assessed", "Avg Rating", "Avg %"],
                axis_rows or [["-"] * 4],
                widths=[95 * mm, 25 * mm, 25 * mm, 25 * mm],
            )
        )
        pdf_path = _write_pdf(output_dir / f"{stem}.pdf", story, landscape_mode=True)

    xlsx_path: Path | None = None
    if "xlsx" in fmt:
        xlsx_path = _write_workbook(
            output_dir / f"{stem}.xlsx",
            {
                "Summary": (
                    ["Metric", "Value"],
                    [
                        ["Department", department],
                        ["Employees", summary.employee_count],
                        ["Average %", summary.average_percentage],
                        ["Minimum %", summary.minimum_percentage],
                        ["Maximum %", summary.maximum_percentage],
                        ["Achieved", summary.achieved_count],
                        ["Gaps", summary.gap_count],
                        ["Unassessed", summary.unassessed_count],
                        ["Critical", summary.critical_gap_count],
                    ],
                ),
                "Employees": (headers, rows),
                "Competency Averages": (["Competency", "Staff Assessed", "Avg Rating", "Avg %"], axis_rows),
            },
        )

    return ReportArtifact(
        name="department_competency_report",
        title=f"Department Competency Report - {department}",
        pdf=pdf_path,
        xlsx=xlsx_path,
        row_count=len(rows),
    )


# ---------------------------------------------------------------------------
# Report 3 - Competency Gap Report
# ---------------------------------------------------------------------------

def competency_gap_report(
    repo: Repository,
    output_dir: Path = DEFAULT_OUTPUT,
    *,
    department: str | None = None,
    fmt: tuple[str, ...] = ("pdf", "xlsx"),
) -> ReportArtifact:
    records = repo.training_needs(department=department)
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"03_competency_gap_{department.replace(' ', '_') if department else 'all'}"

    headers = ["Priority", "Employee No.", "Name", "Position", "Competency", "Category", "Req.", "Cur.", "Short.", "Status"]
    rows = [
        [
            r["priority"],
            r["employeeNumber"],
            r["employeeName"],
            r["positionTitle"],
            r["competencyName"],
            r["category"],
            r["requiredScore"],
            _fmt_rating(r["ratingScore"]),  # type: ignore[arg-type]
            r["shortfall"],
            r["status"],
        ]
        for r in records
    ]

    counts = {str(p): 0 for p in Priority}
    for record in records:
        counts[str(record["priority"])] = counts.get(str(record["priority"]), 0) + 1

    pdf_path: Path | None = None
    if "pdf" in fmt:
        styles = _styles()
        story = _pdf_header(
            "Competency Gap Report",
            f"Scope: {department or 'All departments'} - {len(records)} action items - "
            f"generated {dt.date.today().isoformat()}",
            styles,
        )
        story.append(
            _pdf_table(
                ["Priority Band", "Count"],
                [[priority, counts.get(priority, 0)] for priority in ("Critical", "High", "Medium", "Low")],
                widths=[50 * mm, 30 * mm],
            )
        )
        story.append(Paragraph("All Competency Gaps (most urgent first)", styles["h2"]))
        story.append(
            _pdf_table(
                headers,
                rows or [["-"] * len(headers)],
                widths=[19 * mm, 22 * mm, 38 * mm, 40 * mm, 55 * mm, 26 * mm, 12 * mm, 14 * mm, 13 * mm, 20 * mm],
            )
        )
        pdf_path = _write_pdf(output_dir / f"{stem}.pdf", story, landscape_mode=True)

    xlsx_path: Path | None = None
    if "xlsx" in fmt:
        xlsx_path = _write_workbook(
            output_dir / f"{stem}.xlsx", {"Competency Gaps": (headers, rows)}
        )

    return ReportArtifact(
        name="competency_gap_report",
        title="Competency Gap Report",
        pdf=pdf_path,
        xlsx=xlsx_path,
        row_count=len(rows),
    )


# ---------------------------------------------------------------------------
# Report 4 - Training Needs Report
# ---------------------------------------------------------------------------

def training_needs_report(
    repo: Repository,
    output_dir: Path = DEFAULT_OUTPUT,
    *,
    department: str | None = None,
    fmt: tuple[str, ...] = ("pdf", "xlsx"),
) -> ReportArtifact:
    """Group the gap list into a per-competency training plan.

    A competency needed by three different people is one training course,
    not three - so the actionable column here is *staff affected*, which is
    what a training planner actually needs in order to schedule.
    """
    records = repo.training_needs(department=department)
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"04_training_needs_{department.replace(' ', '_') if department else 'all'}"

    grouped: dict[tuple[str, str], dict[str, object]] = {}
    for record in records:
        key = (str(record["competencyName"]), str(record["category"]))
        entry = grouped.setdefault(
            key,
            {
                "staff": set(),
                "maxShortfall": 0,
                "maxRequired": 0,
                "unassessed": 0,
                "priority": str(record["priority"]),
            },
        )
        entry["staff"].add(str(record["employeeName"]))  # type: ignore[union-attr]
        entry["maxShortfall"] = max(int(entry["maxShortfall"]), int(record["shortfall"]))
        entry["maxRequired"] = max(int(entry["maxRequired"]), int(record["requiredScore"]))
        if record["status"] == str(GapStatus.UNASSESSED):
            entry["unassessed"] = int(entry["unassessed"]) + 1

    headers = ["#", "Competency", "Category", "Priority", "Staff Affected", "Max Req.", "Max Shortfall", "Unassessed", "Action"]
    rows: list[list[object]] = []
    for index, (key, entry) in enumerate(
        sorted(
            grouped.items(),
            key=lambda kv: (
                str(kv[1]["priority"]) != str(Priority.CRITICAL),
                -len(kv[1]["staff"]),  # type: ignore[arg-type]
                -int(kv[1]["maxShortfall"]),
            ),
        ),
        start=1,
    ):
        name, category = key
        if int(entry["unassessed"]) == len(entry["staff"]):  # type: ignore[arg-type]
            action = "Schedule assessment first"
        elif int(entry["unassessed"]):  # type: ignore[arg-type]
            action = "Training + assess remaining"
        else:
            action = "Schedule training"
        rows.append(
            [
                index,
                name,
                category,
                entry["priority"],
                len(entry["staff"]),  # type: ignore[arg-type]
                entry["maxRequired"],
                entry["maxShortfall"],
                entry["unassessed"],
                action,
            ]
        )

    per_employee_rows = [
        [
            r["employeeName"],
            r["employeeNumber"],
            r["department"],
            r["positionTitle"],
            r["priority"],
            r["competencyName"],
            r["requiredScore"],
            _fmt_rating(r["ratingScore"]),  # type: ignore[arg-type]
            r["shortfall"],
            r["status"],
        ]
        for r in records
    ]

    pdf_path: Path | None = None
    if "pdf" in fmt:
        styles = _styles()
        story = _pdf_header(
            "Training Needs Report",
            f"Scope: {department or 'All departments'} - {len(grouped)} distinct training/assessment "
            f"topics covering {len(records)} staff-competency items - "
            f"generated {dt.date.today().isoformat()}",
            styles,
        )
        story.append(Paragraph("Consolidated Training Plan (prioritised)", styles["h2"]))
        story.append(
            _pdf_table(
                headers,
                rows or [["-"] * len(headers)],
                widths=[8 * mm, 62 * mm, 26 * mm, 19 * mm, 22 * mm, 15 * mm, 21 * mm, 20 * mm, 44 * mm],
            )
        )
        story.append(Paragraph("Detail by Employee", styles["h2"]))
        story.append(
            _pdf_table(
                ["Employee", "Emp. No.", "Department", "Position", "Priority", "Competency", "Req.", "Cur.", "Short.", "Status"],
                per_employee_rows or [["-"] * 10],
                widths=[38 * mm, 22 * mm, 30 * mm, 40 * mm, 19 * mm, 55 * mm, 12 * mm, 14 * mm, 13 * mm, 20 * mm],
            )
        )
        pdf_path = _write_pdf(output_dir / f"{stem}.pdf", story, landscape_mode=True)

    xlsx_path: Path | None = None
    if "xlsx" in fmt:
        xlsx_path = _write_workbook(
            output_dir / f"{stem}.xlsx",
            {
                "Training Plan": (headers, rows),
                "By Employee": (
                    ["Employee", "Emp. No.", "Department", "Position", "Priority", "Competency", "Required", "Current", "Shortfall", "Status"],
                    per_employee_rows,
                ),
            },
        )

    return ReportArtifact(
        name="training_needs_report",
        title="Training Needs Report",
        pdf=pdf_path,
        xlsx=xlsx_path,
        row_count=len(rows),
    )


# ---------------------------------------------------------------------------
# Report 5 - Competency Progress Report
# ---------------------------------------------------------------------------

def competency_progress_report(
    repo: Repository,
    employee_id: str,
    output_dir: Path = DEFAULT_OUTPUT,
    *,
    fmt: tuple[str, ...] = ("pdf", "xlsx"),
) -> ReportArtifact:
    profile = repo.get_profile(employee_id)
    history = repo.progress_history(employee_id)
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"05_progress_{profile.employee.employee_number.replace('/', '-')}"

    headers = ["Date", "Cycle", "Assessor", "Total", "Max", "Overall %", "Change", "Per-competency detail"]
    rows: list[list[object]] = []
    for entry in history:
        delta = entry["deltaPercentage"]
        rows.append(
            [
                entry["assessmentDate"],
                entry["cycleName"],
                entry["assessorName"],
                entry["totalRating"],
                entry["maxPossibleRating"],
                f"{entry['overallPercentage']:.1f}%",
                "-" if delta is None else f"{delta:+.1f} pts",
                "Yes" if entry["hasPerCompetencyDetail"] else "No",
            ]
        )

    movement_rows: list[list[object]] = []
    first, latest = (history[0], history[-1]) if len(history) >= 2 else (None, None)
    if first and latest:
        for score in profile.scores:
            movement_rows.append(
                [
                    score.competency_name,
                    score.category,
                    _fmt_rating(score.rating_score),
                    score.required_score,
                    _fmt_pct(score.current_percentage),
                    score.shortfall,
                    str(assess_status(score.rating_score, score.required_score)),
                ]
            )

    caveat = ""
    if history and not all(entry["hasPerCompetencyDetail"] for entry in history):
        caveat = (
            "Note: some assessment cycles were recorded before per-competency detail was "
            "captured, so trend movement can only be shown at the overall-percentage level "
            "for those cycles. Re-assess to restore per-competency trending."
        )

    pdf_path: Path | None = None
    if "pdf" in fmt:
        styles = _styles()
        story = _pdf_header(
            "Competency Progress Report",
            f"{profile.employee.full_name} - {profile.employee.position_title} - "
            f"generated {dt.date.today().isoformat()}",
            styles,
        )
        story.append(Paragraph("Assessment Trend", styles["h2"]))
        story.append(
            _pdf_table(
                headers,
                rows or [["-"] * len(headers)],
                widths=[22 * mm, 44 * mm, 32 * mm, 14 * mm, 14 * mm, 20 * mm, 20 * mm, 40 * mm],
            )
        )
        if caveat:
            story.append(Spacer(1, 6))
            story.append(Paragraph(caveat, styles["small"]))
        if movement_rows:
            story.append(Paragraph("Current Standing by Competency", styles["h2"]))
            story.append(
                _pdf_table(
                    ["Competency", "Category", "Current", "Required", "Current %", "Shortfall", "Status"],
                    movement_rows,
                    widths=[68 * mm, 30 * mm, 20 * mm, 20 * mm, 20 * mm, 20 * mm, 28 * mm],
                )
            )
        pdf_path = _write_pdf(output_dir / f"{stem}.pdf", story, landscape_mode=True)

    xlsx_path: Path | None = None
    if "xlsx" in fmt:
        xlsx_path = _write_workbook(
            output_dir / f"{stem}.xlsx",
            {
                "Progress Trend": (headers, rows),
                "Current Standing": (
                    ["Competency", "Category", "Current", "Required", "Current %", "Shortfall", "Status"],
                    movement_rows,
                ),
            },
        )

    return ReportArtifact(
        name="competency_progress_report",
        title=f"Competency Progress Report - {profile.employee.full_name}",
        pdf=pdf_path,
        xlsx=xlsx_path,
        row_count=len(rows),
    )


def assess_status(rating: int | None, required: int) -> str:
    if rating is None:
        return str(GapStatus.UNASSESSED)
    return str(GapStatus.ACHIEVED if rating >= required else GapStatus.GAP)
